// Bilingual content for "Tel Aviv HaCharedit"

export const CONTENT = {
  he: {
    nav: {
      home: "דף הבית",
      manifesto: "מניפסט",
      map: "מפת החולות",
      souls: "דמויות",
      timeline: "ציר הזמן",
      directory: "מדריך השירותים",
    },
    edition: "מהדורה א׳ · כרך ראשון · אפריל 2026",
    hero: {
      kicker: "פוליו דיגיטלי · ארכיון 1909–2026",
      titleA: "תל אביב",
      titleB: "החרדית",
      subtitle: "לא אורחים — חלק מיסודותיה",
    },
    heroCorner: { line1: "אוסף ארכיוני", line2: "תיעוד והיסטוריה" },
    scrollCue: "גלול",
    manifesto: {
      kicker: "מניפסט",
      title: "לא אורחים. חלק מיסודותיה.",
      sub: "טור פתיחה · מהדורה א׳",
      colA: "בעוד החולות עוד לחים מתפילת הבוקר, כבר נטעו במקום הזה ישיבות, חצרות, ובתי כנסת קטנים שנעלמו בין הסמטאות. ההיסטוריה הקנונית של תל אביב סיפרה לנו על חברת \"אחוזת בית\" ועל הגרלת הצדפים, אבל שכחה לציין מי בדיוק חי על המגרשים הסמוכים, מי פתח חנות גלנטריה, ומי קבע את המזוזה הראשונה.",
      colB: "האתר הזה הוא ניסיון לשחזר את הקול הזה — לא כיריב היסטורי, אלא כשותף שהיה שם מהיום הראשון. הקהילה החרדית של תל אביב היא חוט שזור בבד העירוני: בכרם התימנים, בשפירא, בשכונת התקווה, ולאורך אלנבי. הסיפור הזה הוא חלק מהעיר, לא הערת שוליים שלה.",
    },
    map: {
      kicker: "גיאוגרפיה · אטלס היסטורי",
      title: "מפת החולות",
      lede: "שרטוט של מהנדס עיר משנות ה־30, מונח על שולחן עץ. כל סיכה מסמנת קהילה. בלחיצה — צוללים אל סיפור.",
      meta: { title: "אלנבי וסביבותיה", sub: "קנה מידה 1:8000 · 1936" },
    },
    neighborhoods: [
      {
        id: "shapira", name: "שכונת שפירא", eng: "Shapira",
        founded: "1924", communities: "11", rabbis: "23",
        story: "שכונה בנויה על שיירי החולות הדרומיים, שהפכה לצומת חרדי תוסס בין מוסכים לבתי תפילה. בית הכנסת \"אהל יעקב\", החבוי בין סדנאות ברזל, ידוע כמקום שבו התקיימו שיעורי תלמוד מ־1929 ועד היום.",
        x: 30, y: 65,
        streetKeywords: ["שפירא", "חכמי ישראל", "משה דיין", "הר ציון", "יד חרוצים"],
      },
      {
        id: "kerem", name: "כרם התימנים", eng: "Kerem HaTeimanim",
        founded: "1906", communities: "8", rabbis: "17",
        story: "סמטאות צרות שהשתמרו כמעט במלואן. הקהילה התימנית הקימה כאן בתי כנסת קטנים שכל אחד מהם משמר נוסח אחר — נוסח בלאדי, נוסח שאמי, נוסח ארץ ישראל הקדום.",
        x: 55, y: 38,
        streetKeywords: ["כרם התימנים", "כרם חמד", "קלישר", "רמב\"ם", "נחלת בנימין", "המבורגר", "מקווה ישראל", "מלצ", "טבריה"],
      },
      {
        id: "florentin", name: "פלורנטין", eng: "Florentin",
        founded: "1927", communities: "6", rabbis: "12",
        story: "פעם רובע מסחר עם בתי מדרש בקומות העליונות מעל החנויות. סלוניקאים, חסידי גור, וגם מקובלים — כולם שיתפו אותו רחוב, אותה מכבסה ציבורית, ואותו ויכוח על מי קונה את הציצית.",
        x: 42, y: 75,
        streetKeywords: ["פלורנטין", "אילת", "וולפסון", "מטלון", "אברבנאל", "הכובשים", "יחיאלי", "בן עטר", "החלוצים", "ידידיה פרנקל", "הרצל רוזנבלום"],
      },
      {
        id: "neve-tzedek", name: "נווה צדק", eng: "Neve Tzedek",
        founded: "1887", communities: "5", rabbis: "9",
        story: "השכונה היהודית הראשונה מחוץ ליפו. כאן הוקם בית הכנסת הראשון של תל אביב הקדומה, וכאן התגוררו הרב מבריסק והסופר עגנון בקרבת מקום, באירוניה היסטורית של בניין אחד.",
        x: 70, y: 55,
        streetKeywords: ["נווה צדק", "פינס", "שטיינר", "שבזי", "נחמני"],
      },
      {
        id: "hatikva", name: "שכונת התקווה", eng: "HaTikva",
        founded: "1935", communities: "9", rabbis: "14",
        story: "קהילות עולים מתימן, עיראק וכורדיסטן בנו רשת של בתי כנסת זעירים, חלקם בני חדר וחצי. הם פעלו במקביל לפעילות הציונית הסוציאליסטית של השכונה — ולעיתים, בני אותה משפחה נחלקו בין השניים.",
        x: 25, y: 30,
        streetKeywords: ["שכונת התקווה", "אצ\"ל", "אצל", "אצ״ל"],
      },
    ],
    souls: {
      kicker: "פורטרטים · היכל הדמויות",
      title: "הנשמות",
      lede: "רבנים, עסקנים, מורות ובעלי מלאכה. רחפו עם העכבר על דמות לחשיפת הסיפור.",
    },
    soulsList: [
      { id: 1, name: "הרב משה אביגדור עמיאל", years: "1883—1946", role: "הרב הראשי", bio: "הרב הראשי האשכנזי של תל אביב מ־1936. ניסה לגשר בין הציבור החרדי לעיר החילונית הצומחת. ידוע ב\"שיעורי הבוקר\" שנמסרו ברחוב יבנה.", x: 8, y: 6, delay: 0,
        linkedSynagogue: { name: "בית הכנסת הגדול תל-אביב", address: "אלנבי 110", label: "ניהל מכאן את הקהילה" } },
      { id: 2, name: "הרבנית ברכה קפח", years: "1923—2013", role: "מחנכת ופעלתנית", bio: "פעילה תימנית בולטת שייסדה רשת של מועדוני נשים בכרם התימנים. זכתה בפרס ישראל ב־1999 על עבודתה החינוכית.", x: 28, y: 32, delay: 1.2,
        linkedSynagogue: { name: "\"שבת אחים\"", address: "כרם התימנים רח' קלישר 5", label: "פעלה בכרם התימנים" } },
      { id: 3, name: "ר׳ שלמה זלמן אויערבך", years: "1910—1995", role: "פוסק", bio: "אחד מגדולי הפוסקים של המאה ה־20. ביקר בתל אביב פעמים רבות והכריע בשאלות הלכתיות הנוגעות לחיי העיר המודרנית — מעלית בשבת, הפרשת תרומות בחנויות.", x: 55, y: 12, delay: 2.4 },
      { id: 4, name: "מרים זבדיה", years: "1898—1972", role: "מיילדת השכונה", bio: "מיילדת ידועה בשפירא ובהתקווה. ילדה דורות שלמים בבתים, ושמרה ביומן עץ קטן את שמות כל התינוקות עד יומה האחרון.", x: 78, y: 38, delay: 3.6 },
      { id: 5, name: "האדמו״ר מבויאן", years: "1922—1971", role: "אדמו״ר", bio: "ייסד את חצר בויאן בתל אביב לאחר השואה. החצר הקטנה ברחוב יונה הנביא הפכה למרכז עבור פליטים שחיפשו זיכרון של עיירה.", x: 12, y: 60, delay: 4.8,
        linkedSynagogue: { name: "סדיגורה - כנסת מרדכי", address: "פנקס 41", label: "חצר אחות (שושלת רוז'ין)" } },
      { id: 6, name: "ר׳ עובדיה הדאיה", years: "1890—1969", role: "מקובל וראש ישיבה", bio: "ראש ישיבת \"בית אל\" המקובלת. ניהל את הישיבה ברחוב יהודה הלוי במשך עשרות שנים, והיה מהבולטים בקבלה הספרדית במאה ה־20.", x: 42, y: 56, delay: 6.0,
        linkedSynagogue: { name: "\"בית אל\" עולי משהד", address: "יהושע בן נון 63", label: "ממשיכי נוסח בית אל" } },
      { id: 7, name: "פייגה לאה אלטוסקי", years: "1905—1989", role: "מורת בית ספר", bio: "מורה ב\"בית יעקב\" הראשון בתל אביב, נפתח ב־1937 בדירה ברחוב נחלת בנימין. לימדה דורות של תלמידות בעברית וביידיש לסירוגין.", x: 70, y: 64, delay: 7.2 },
      { id: 8, name: "ר׳ יוסף קאפח", years: "1917—2000", role: "חכם ומתרגם", bio: "מגדולי חכמי תימן בדור האחרון. ישב בירושלים אך הגיע לתל אביב מדי שבוע למסור שיעורים בכרם, ועסק במהדורות מדעיות של ספרי הרמב\"ם.", x: 25, y: 80, delay: 8.4,
        linkedSynagogue: { name: "\"עץ חיים\"", address: "טבריה 5", label: "מסר שיעורים בכרם" } },
    ],
    timeline: {
      kicker: "כרוניקה · 1887—2026",
      title: "הקו הזוהר",
      lede: "דרך מתעקלת אל האופק. אנחנו מתחילים בחולות וגומרים במגדלים — ובכל פרק, החיים החרדיים נכחו.",
    },
    events: [
      { year: "1887", title: "נווה צדק", desc: "השכונה היהודית הראשונה מחוץ ליפו. בית כנסת ספרדי קטן הוקם כעבור שנתיים.",
        link: { type: 'neighborhood', id: 'neve-tzedek', label: 'מפה: נווה צדק' } },
      { year: "1909", title: "אחוזת בית", desc: "הגרלת הצדפים. מבין 60 משפחות־הייסוד — לפחות שמונה היו דתיות שומרות מסורת." },
      { year: "1924", title: "ישיבת היישוב החדש", desc: "אחת הישיבות הראשונות בעיר, בייסוד הרב משה סולוביציק.",
        link: { type: 'neighborhood', id: 'shapira', label: 'מפה: שפירא' } },
      { year: "1936", title: "הרב עמיאל", desc: "הרבנות הראשית האשכנזית מתמסדת. תל אביב הופכת למוקד פסיקה הלכתי.",
        link: { type: 'synagogue', name: 'בית הכנסת הגדול תל-אביב', address: 'אלנבי 110', label: 'בית הכנסת הגדול' } },
      { year: "1948", title: "המדינה", desc: "פליטים מאירופה נטמעים בשכונות הדרום. מאות מניינים חדשים נפתחים בתוך שנתיים.",
        link: { type: 'neighborhood', id: 'hatikva', label: 'מפה: התקווה' } },
      { year: "1967", title: "פריחת בתי המדרש", desc: "מוסדות חינוך חרדיים מתרחבים. \"בית יעקב\" התל־אביבי קולט אלפי תלמידות." },
      { year: "1981", title: "מאבקי השבת", desc: "פרק טעון. קיר הפשקווילים מתמלא. השיח הציבורי מתחדד." },
      { year: "2009", title: "המאה לעיר", desc: "תל אביב חוגגת 100. בעצרת המרכזית — מקום לקנטור של ישיבת פוניבז׳." },
      { year: "2026", title: "מנייני המשרדים", desc: "מגדלי ההייטק חולקים שטח עם מנייני מנחה במגדל אלון, רוטשילד 22, ושרונה.",
        link: { type: 'category', id: 'office-minyanim', label: 'מנייני משרדים במדריך' } },
    ],
    directory: {
      kicker: "מדריך · העיר החיה",
      title: "מדריך השירותים",
      lede: "כל מה שצריך לחיים דתיים בתל אביב היום — בתי כנסת, מקוואות, מסעדות כשרות, מנייני משרדים, ומפת עירוב. נתונים אמיתיים מהרשת + הוספה ידנית שלך.",
      searchPlaceholder: "חיפוש בקטגוריה הנוכחית...",
      empty: "לא נמצאו תוצאות מתאימות",
      manualEmpty: "קטגוריה זו מבוססת על הזנה ידנית. אין מקור ציבורי מאורגן. הוסף את הערך הראשון:",
      addFirst: "הוסף ערך ראשון",
      source: "מקור",
      userAdded: "הוספות שלך",
      addBtn: "הוסף",
      addTitle: "הוספת ערך חדש",
      addHint: "הערך נשמר אוטומטית בדפדפן (localStorage). השתמש בכפתור ייצוא כדי להוריד JSON ולהחליף את הקובץ ב-src/data/",
      exportBtn: "ייצא JSON",
      cancel: "ביטול",
      save: "שמור",
      delete: "מחק ערך",
      deleteConfirm: "למחוק ערך זה?",
      noteHint: "לחץ לסיפור היסטורי",
      didYouKnow: "הידעת?",
      openMaps: "פתח בגוגל מפות",
      heritageFilter: "היסטוריים",
      heritageHint: "הצג רק בתי כנסת עם רקע היסטורי מתועד",
      statsTotal: "ערכים פעילים",
      statsNotes: "הערות 'הידעת?'",
      statsSources: "מקורות מאומתים",
      statsUpdated: "עודכן",
      statsUpdatedDate: "אפר׳ 2026",
      routeTitle: "מסלול היסטורי מומלץ",
      routeDesc: "12 בתי כנסת מתועדים — סיור הליכה דרך תל אביב הדתית.",
      routeOpenMaps: "פתח מסלול בגוגל",
      routeDownload: "הורד מסלול JSON",
    },
    zmanim: {
      kicker: "זמני היום · תל אביב",
      loading: "טוען זמנים...",
      error: "לא ניתן לטעון את הזמנים. נסה שוב מאוחר יותר.",
      source: "מקור הזמנים",
    },
    globalSearch: {
      trigger: "חיפוש בכל האתר",
      shortcutHint: "Ctrl+K לחיפוש מהיר",
      placeholder: "חפש בית כנסת, מסעדה, מקווה, גמ״ח...",
      hint: "התחל להקליד — חיפוש בכל 1408 הערכים",
      empty: "לא נמצאו תוצאות",
      navigate: "ניווט",
      select: "בחירה",
      close: "סגירה",
    },
    colophon: {
      mark: "ת״א.ח",
      vol: "מהדורה א׳",
      volSub: "Volume I · April 2026",
      credits: "קרדיטים",
      creditsList: ["מחקר ארכיוני: צוות הפוליו", "תצלומים: ארכיון העיר ת״א-יפו", "ארכיון בית עגנון", "ספריית הקונגרס", "מדריך בתי כנסת: כיפה"],
      contact: "צור קשר",
      contactList: ["folio@example.org", "תרומה לארכיון", "הגש זיכרון אישי"],
      bottom: "© 2026 פוליו תל אביב החרדית · כל הזכויות שמורות",
      issue: "Issue 01 · 09",
    },
  },
  en: {
    nav: {
      home: "Home", manifesto: "Manifesto", map: "Sands Map",
      souls: "Figures", timeline: "Timeline", directory: "Directory",
    },
    edition: "Volume I · First Issue · April 2026",
    hero: {
      kicker: "Digital Folio · Archive 1909–2026",
      titleA: "The Other",
      titleB: "White City",
      subtitle: "Not guests — part of its foundations",
    },
    heroCorner: { line1: "Archival Collection", line2: "Documentation & History" },
    scrollCue: "Scroll",
    manifesto: {
      kicker: "Manifesto",
      title: "Not guests. Part of its foundations.",
      sub: "Opening Column · Volume I",
      colA: "While the dunes were still wet from the morning prayer, yeshivas, courts, and small prayer houses had already taken root here — places that vanished between the alleys. The canonical history of Tel Aviv tells us about \"Ahuzat Bayit\" and the seashell lottery, but forgets to mention exactly who lived on the adjacent plots, who opened a haberdashery, and who hung the very first mezuzah.",
      colB: "This site is an attempt to restore that voice — not as a historical rival, but as a partner who was here from the very first day. Tel Aviv's Haredi community is a thread woven through the urban fabric: in Kerem HaTeimanim, in Shapira, in HaTikva, and along Allenby. This story is part of the city, not a footnote to it.",
    },
    map: {
      kicker: "Geography · Historical Atlas",
      title: "The Sands Map",
      lede: "A 1930s city engineer's drawing on a wooden desk. Each pin marks a community. Click — and dive into a story.",
      meta: { title: "Allenby & Surroundings", sub: "Scale 1:8000 · 1936" },
    },
    neighborhoods: [
      { id: "shapira", name: "Shapira", eng: "שפירא", founded: "1924", communities: "11", rabbis: "23",
        story: "A neighborhood built on the southern dunes' remains, which became a vibrant Haredi crossroads between auto-shops and prayer houses. The Ohel Yaakov synagogue, hidden among iron workshops, has hosted Talmud classes since 1929.",
        x: 30, y: 65,
        streetKeywords: ["שפירא", "חכמי ישראל", "משה דיין", "הר ציון", "יד חרוצים"] },
      { id: "kerem", name: "Kerem HaTeimanim", eng: "כרם התימנים", founded: "1906", communities: "8", rabbis: "17",
        story: "Narrow alleys preserved almost entirely. The Yemenite community established small synagogues, each preserving a different rite — Baladi, Shami, ancient Eretz Yisrael.",
        x: 55, y: 38,
        streetKeywords: ["כרם התימנים", "כרם חמד", "קלישר", "רמב\"ם", "נחלת בנימין", "המבורגר", "מקווה ישראל", "מלצ", "טבריה"] },
      { id: "florentin", name: "Florentin", eng: "פלורנטין", founded: "1927", communities: "6", rabbis: "12",
        story: "Once a commerce quarter with study halls on the upper floors above the shops. Salonikans, Gur Hasidim, and Kabbalists — all shared the same street, the same public laundry, and the same argument over who buys the tzitzit.",
        x: 42, y: 75,
        streetKeywords: ["פלורנטין", "אילת", "וולפסון", "מטלון", "אברבנאל", "הכובשים", "יחיאלי", "בן עטר", "החלוצים", "ידידיה פרנקל", "הרצל רוזנבלום"] },
      { id: "neve-tzedek", name: "Neve Tzedek", eng: "נווה צדק", founded: "1887", communities: "5", rabbis: "9",
        story: "The first Jewish neighborhood outside Jaffa. Tel Aviv's first synagogue was built here, and the Brisker Rav and the writer Agnon lived nearby — in a historical irony, in the same building.",
        x: 70, y: 55,
        streetKeywords: ["נווה צדק", "פינס", "שטיינר", "שבזי", "נחמני"] },
      { id: "hatikva", name: "HaTikva", eng: "שכונת התקווה", founded: "1935", communities: "9", rabbis: "14",
        story: "Immigrant communities from Yemen, Iraq and Kurdistan built a network of tiny synagogues, some only a room and a half. They operated alongside the neighborhood's socialist Zionist activity — and at times, members of the same family split between the two.",
        x: 25, y: 30,
        streetKeywords: ["שכונת התקווה", "אצ\"ל", "אצל", "אצ״ל"] },
    ],
    souls: {
      kicker: "Portraits · Hall of Figures",
      title: "The Souls",
      lede: "Rabbis, activists, teachers and craftsmen. Hover a figure to reveal their story.",
    },
    soulsList: [
      { id: 1, name: "Rabbi M. A. Amiel", years: "1883—1946", role: "Chief Rabbi", bio: "Ashkenazi Chief Rabbi of Tel Aviv from 1936. Sought to bridge the Haredi public with the growing secular city. Known for his \"morning lessons\" delivered on Yavne Street.", x: 8, y: 6, delay: 0,
        linkedSynagogue: { name: "בית הכנסת הגדול תל-אביב", address: "אלנבי 110", label: "Led the community here" } },
      { id: 2, name: "Rabbanit Bracha Kapach", years: "1923—2013", role: "Educator", bio: "A prominent Yemenite activist who founded a network of women's centers in Kerem HaTeimanim. Awarded the Israel Prize in 1999 for her educational work.", x: 28, y: 32, delay: 1.2,
        linkedSynagogue: { name: "\"שבת אחים\"", address: "כרם התימנים רח' קלישר 5", label: "Active in Kerem HaTeimanim" } },
      { id: 3, name: "R. S. Z. Auerbach", years: "1910—1995", role: "Halachic Authority", bio: "One of the leading halachic authorities of the 20th century. Visited Tel Aviv often and ruled on matters of urban modern life — Shabbat elevators, tithing in stores.", x: 55, y: 12, delay: 2.4 },
      { id: 4, name: "Miriam Zvadya", years: "1898—1972", role: "Neighborhood Midwife", bio: "A renowned midwife in Shapira and HaTikva. Delivered entire generations at home, and kept the names of every infant in a small wooden ledger until her last day.", x: 78, y: 38, delay: 3.6 },
      { id: 5, name: "The Boyaner Rebbe", years: "1922—1971", role: "Hasidic Rebbe", bio: "Established the Boyan court in Tel Aviv after the Holocaust. The small court on Yona HaNavi street became a refuge for survivors seeking memory of their shtetl.", x: 12, y: 60, delay: 4.8,
        linkedSynagogue: { name: "סדיגורה - כנסת מרדכי", address: "פנקס 41", label: "Sister court (Ruzhin lineage)" } },
      { id: 6, name: "R. Ovadia Hadaya", years: "1890—1969", role: "Kabbalist · Rosh Yeshiva", bio: "Head of the kabbalist Beit-El yeshiva. Led it on Yehuda Halevi street for decades and was among the foremost figures in 20th-century Sephardic Kabbalah.", x: 42, y: 56, delay: 6.0,
        linkedSynagogue: { name: "\"בית אל\" עולי משהד", address: "יהושע בן נון 63", label: "Continuators of Beit El rite" } },
      { id: 7, name: "Feiga Leah Altusky", years: "1905—1989", role: "Schoolteacher", bio: "Teacher at Tel Aviv's first Beit Yaakov, opened in 1937 in an apartment on Nachalat Binyamin. Taught generations of students in alternating Hebrew and Yiddish.", x: 70, y: 64, delay: 7.2 },
      { id: 8, name: "R. Yosef Kapach", years: "1917—2000", role: "Sage & Translator", bio: "One of the great Yemenite sages of the last generation. Lived in Jerusalem but came to Tel Aviv weekly to teach in the Kerem, while preparing scholarly editions of Maimonides.", x: 25, y: 80, delay: 8.4,
        linkedSynagogue: { name: "\"עץ חיים\"", address: "טבריה 5", label: "Taught in Kerem HaTeimanim" } },
    ],
    timeline: {
      kicker: "Chronicle · 1887—2026",
      title: "The Golden Curve",
      lede: "A road bending toward the horizon. We start in the dunes and end in towers — and at every chapter, Haredi life was present.",
    },
    events: [
      { year: "1887", title: "Neve Tzedek", desc: "The first Jewish neighborhood outside Jaffa. A small Sephardic synagogue was built two years later.",
        link: { type: 'neighborhood', id: 'neve-tzedek', label: 'Map: Neve Tzedek' } },
      { year: "1909", title: "Ahuzat Bayit", desc: "The seashell lottery. Of 60 founding families — at least eight were tradition-observant." },
      { year: "1924", title: "Yeshivat HaYishuv", desc: "One of the first yeshivas in the city, founded by Rabbi Moshe Soloveitchik.",
        link: { type: 'neighborhood', id: 'shapira', label: 'Map: Shapira' } },
      { year: "1936", title: "Rabbi Amiel", desc: "Ashkenazi chief rabbinate institutionalized. Tel Aviv becomes a halachic ruling center.",
        link: { type: 'synagogue', name: 'בית הכנסת הגדול תל-אביב', address: 'אלנבי 110', label: 'The Great Synagogue' } },
      { year: "1948", title: "The State", desc: "Refugees from Europe are absorbed in southern neighborhoods. Hundreds of new minyanim open within two years.",
        link: { type: 'neighborhood', id: 'hatikva', label: 'Map: HaTikva' } },
      { year: "1967", title: "Study halls flourish", desc: "Haredi educational institutions expand. The Tel Aviv Beit Yaakov takes in thousands of students." },
      { year: "1981", title: "Shabbat Disputes", desc: "A charged chapter. The pashkevil wall fills up. Public discourse sharpens." },
      { year: "2009", title: "The City's Centennial", desc: "Tel Aviv celebrates 100. At the central ceremony — a place for a Ponevezh yeshiva chant." },
      { year: "2026", title: "Office Minyanim", desc: "High-tech towers share space with mincha minyanim in Alon Tower, Rothschild 22, and Sarona.",
        link: { type: 'category', id: 'office-minyanim', label: 'Office Minyanim in Directory' } },
    ],
    directory: {
      kicker: "Directory · The Living City",
      title: "Services Directory",
      lede: "Everything you need for religious life in Tel Aviv today — synagogues, mikvaot, kosher restaurants, office minyanim, and eruv map. Real web data + your own additions.",
      searchPlaceholder: "Search the current category...",
      empty: "No matching results",
      manualEmpty: "This category is manual-entry only — no organized public source available. Add the first entry:",
      addFirst: "Add first entry",
      source: "Source",
      userAdded: "Your additions",
      addBtn: "Add",
      addTitle: "Add new entry",
      addHint: "Saved automatically to browser localStorage. Use Export to download a JSON file to replace src/data/",
      exportBtn: "Export JSON",
      cancel: "Cancel",
      save: "Save",
      delete: "Delete entry",
      deleteConfirm: "Delete this entry?",
      noteHint: "Click for historical note",
      didYouKnow: "Did you know?",
      openMaps: "Open in Google Maps",
      heritageFilter: "Heritage",
      heritageHint: "Show only synagogues with documented historical context",
      statsTotal: "Active Entries",
      statsNotes: "'Did you know?' Notes",
      statsSources: "Verified Sources",
      statsUpdated: "Updated",
      statsUpdatedDate: "Apr '26",
      routeTitle: "Suggested Heritage Route",
      routeDesc: "12 documented synagogues — a walking tour through religious Tel Aviv.",
      routeOpenMaps: "Open route in Maps",
      routeDownload: "Download route JSON",
    },
    zmanim: {
      kicker: "Today's Times · Tel Aviv",
      loading: "Loading times...",
      error: "Could not load times. Please try again later.",
      source: "Times source",
    },
    globalSearch: {
      trigger: "Search everything",
      shortcutHint: "Ctrl+K to quick search",
      placeholder: "Search synagogues, restaurants, mikvaot, gemachs...",
      hint: "Start typing — search across all 1408 entries",
      empty: "No matches found",
      navigate: "navigate",
      select: "select",
      close: "close",
    },
    colophon: {
      mark: "T.A.H",
      vol: "Volume I",
      volSub: "First Issue · April 2026",
      credits: "Credits",
      creditsList: ["Archival research: Folio team", "Photos: Tel Aviv–Yafo City Archive", "Agnon House Archive", "Library of Congress", "Synagogue directory: Kipa"],
      contact: "Contact",
      contactList: ["folio@example.org", "Donate to the archive", "Submit a personal memory"],
      bottom: "© 2026 The Other White City Folio · All rights reserved",
      issue: "Issue 01 · 09",
    },
  },
};
